// ShiftMD v3.6 - Dvojezični sistem (srpski i engleski) sa opsezima datuma

const translations = {
  sr: {
    // Navigacija
    nav_brand: "🩺 ShiftMD v3.6",
    nav_home: "🏠 Početna",
    nav_about: "ℹ️ O sistemu",
    nav_guide: "📖 Uputstvo",
    nav_lang_sr: "🇷🇸 SR",
    nav_lang_en: "🇬🇧 EN",
    
    // Footer
    footer_cikt: "Centar za informacione i komunikacione tehnologije",
    footer_university: "Univerzitet u Beogradu, Medicinski fakultet",
    
    // Index strana
    page_title: "ShiftMD v3.6 - Raspored dežurstava",
    heading: "ShiftMD v3.6",
    subtitle: "Sistem za raspored dežurstava lekara",
    form_hospital: "Naziv ustanove",
    form_month: "Mesec", form_year: "Godina",
    form_month_placeholder: "Mesec", form_year_placeholder: "Godina",
    
    // Tipovi dežurstava
    form_duty_type1_label: "Dežurstvo - Tip 1",
    form_duty_type2_toggle: "Da li je potreban dodatni tip dežurstva za druge datume?",
    form_duty_type2_label: "Dežurstvo - Tip 2",
    form_custom_names_label: "Prilagođena imena tipova dežurstava:",
    form_custom_name1_placeholder: "Naziv za Tip 1 (npr. Obično dežurstvo)",
    form_custom_name2_placeholder: "Naziv za Tip 2 (npr. Hitno dežurstvo)",
    form_type1_dates: "Dani za Tip 1:",
    form_type2_dates: "Dani za Tip 2:",
    calendar_placeholder_type1: "Izaberite mesec i godinu za Tip 1",
    calendar_placeholder_type2: "Izaberite mesec i godinu za Tip 2",
    
    form_duty_count_label: "Broj dežurnih po danu:",
    form_duty_count_hint: "Koliko ukupno dežurstava (1/1) treba popuniti po danu",
    form_allow_less_label: "Dozvoli da bude manje od 50% specijalista među dežurnima?",
    form_allow_less_hint_checked: "Ako je čekirano: specijalista će obavezno biti glavni dežurni, ali udeo specijalista može biti manji od 50%.",
    form_allow_less_hint_unchecked: "Ako NIJE čekirano: najmanje 50% dežurnih moraju biti specijalisti.",
    form_ranked_label: "Rangirani dežurni (timovi)?",
    form_ranked_hint_checked: "Ako je čekirano: svaki dan mora imati lekare svih rangova. Broj dežurnih = broj rangova.",
    form_ranked_hint_unchecked: "Ako NIJE čekirano: raspodela po standardnom algoritmu.",
    form_excel_label: "📂 Otpremite Excel fajl sa spiskom lekara:",
    form_excel_hint: "Dozvoljeni formati: .xlsx, .xls",
    form_demo_link_sr: "📥 Preuzmi primer (srpska zaglavlja)",
    form_demo_link_en: "📥 Preuzmi primer (engleska zaglavlja)",
    form_submit: "⚡ Generiši raspored",
    calendar_placeholder: "Izaberite mesec i godinu da biste videli kalendar",
    calendar_error: "Neispravan mesec ili godina.",
    
    day_mon: "Pon", day_tue: "Uto", day_wed: "Sre", day_thu: "Čet", day_fri: "Pet", day_sat: "Sub", day_sun: "Ned",
    month_1: "Januar", month_2: "Februar", month_3: "Mart", month_4: "April", month_5: "Maj", month_6: "Jun",
    month_7: "Jul", month_8: "Avgust", month_9: "Septembar", month_10: "Oktobar", month_11: "Novembar", month_12: "Decembar",
    
    status_loading: "ShiftMD računa raspored i generiše Excel fajl...",
    status_success: "✅ ShiftMD: Raspored generisan za {duration}s!",
    status_error_no_excel: "Molimo otpremite Excel fajl.",
    status_error_no_dates: "Izaberite bar jedan dan dežurstva.",
    status_error_no_dates1: "Morate izabrati bar jedan dan za Tip 1.",
    status_error_no_dates2: "Morate izabrati bar jedan dan za Tip 2.",
    status_error_overlap: "Datumi za Tip 1 i Tip 2 se preklapaju!",
    status_error_no_count: "Broj dežurnih po danu mora biti najmanje 1.",
    status_error_no_file: "Nema generisanog fajla za preuzimanje.",
    
    download_btn: "📥 Preuzmi Excel raspored",
    download_btn_with_name: "📥 Preuzmi Excel raspored ({filename})",
    result_title: "RASPORED DEŽURSTAVA",
    result_hospital: "Ustanova", result_month: "Mesec", result_duty_count: "Broj dežurstava po danu",
    result_rule: "Pravilo", result_rule_strict: "Minimum 50% specijalista", result_rule_relaxed: "Obavezan glavni specijalista",
    result_ranked: "Rangirani timovi", result_time: "Vreme", result_seconds: "sekundi",
    result_no_data: "⚠️ Nema generisanih dežurstava.",
    
    // O sistemu
    about_title: "ℹ️ O sistemu ShiftMD",
    about_subtitle: "Inteligentni sistem za pravednu raspodelu dežurstava sa fokusom na sprečavanje burnout-a",
    about_mission_title: "🎯 Naša misija",
    about_mission_text: "ShiftMD je stvoren sa jednim ciljem: eliminisati nepravdu u raspodeli dežurstava i zaštititi zdravstvene radnike od prekomernog opterećenja.",
    about_features_title: "✨ Ključne mogućnosti",
    about_feature_1_title: "Pravedna raspodela", about_feature_1_text: "Napredni algoritam osigurava da svi lekari dobiju približno isto opterećenje",
    about_feature_2_title: "Burnout zaštita", about_feature_2_text: "Minimum 2 dana razmaka, limitirani vikendi, maksimalno opterećenje",
    about_feature_3_title: "Poštovanje želja", about_feature_3_text: "Lekari mogu naznačiti datume kada žele da dežuraju",
    about_feature_4_title: "\"Ne može\" se poštuje", about_feature_4_text: "Datumi kada lekar ne može da dežura se apsolutno poštuju",
    about_feature_5_title: "Glavni dežurni", about_feature_5_text: "Automatski dodeljuje specijalistu koji može biti glavni",
    about_feature_6_title: "Opsezi datuma", about_feature_6_text: "Unesite godišnji odmor kao opseg: 22-03-2026 do 28-03-2026",
    about_feature_7_title: "Dva tipa dežurstava", about_feature_7_text: "Podrška za različite tipove dežurstava u istom mesecu",
    about_feature_8_title: "Rangirani timovi", about_feature_8_text: "Podrška za hirurške timove sa rangiranim dežurnima",
    about_logic_title: "🧠 Logika rasterećenja i sprečavanja burnout-a",
    about_logic_box_title: "🛡️ Burnout prevencija - srce sistema",
    about_logic_box_text: "ShiftMD koristi sofisticirani scoring algoritam koji uzima u obzir 9 različitih faktora.",
    about_limits_title: "📊 Maksimalni limiti:",
    about_limit_1: "Max dana dežurstva: proporcionalno broju lekara + 2",
    about_limit_2: "Max opterećenje: 30% ukupnog kapaciteta po lekaru",
    about_limit_3: "Max vikenda: proporcionalno broju vikend dana + 1",
    about_limit_4: "Min razmak: 2 dana između dežurstava (apsolutno pravilo)",
    about_cta_title: "🚀 Spremni za pravednije dežurstvo?",
    about_cta_text: "Vratite se na početnu stranu i generišite svoj prvi raspored.",
    about_cta_btn: "⚡ Generiši raspored",
    
    // Uputstvo
    guide_title: "📖 Uputstvo za korišćenje",
    guide_subtitle: "Korak po korak vodič za generisanje rasporeda dežurstava",
    guide_step1_title: "1️⃣ Priprema Excel fajla sa lekarima",
    guide_step1_text: "Ovo je najvažniji korak. Excel fajl mora imati tačno određene kolone sa ispravnim nazivima:",
    guide_table_header_col: "Kolona", guide_table_header_required: "Obavezno", guide_table_header_desc: "Opis", guide_table_header_values: "Dozvoljene vrednosti",
    guide_col_name_desc: "Puno ime i prezime lekara", guide_col_name_values: "Bilo koji tekst",
    guide_col_seniority_desc: "Arbitrarna vrednost od 1 do 15. Manji broj = veći prioritet", guide_col_seniority_values: "Broj od 1 do 15",
    guide_col_chief_desc: "Da li lekar može biti glavni dežurni? (mora biti specijalista)", guide_col_chief_values: "DA/YES ili NE/NO",
    guide_col_role_desc: "Vrsta lekara", guide_col_role_values: "specijalista/specialist ili specijalizant/resident",
    guide_col_share_desc: "Koliki deo punog dežurstva lekar može da pokrije", guide_col_share_values: "celo/full, polovina/half, trećina/third, četvrtina/quarter, osmina/eighth",
    guide_col_unavailable_desc: "Datumi kada lekar NE MOŽE da dežura. Pojedinačni datumi ili opsezi ('do'/'to') odvojeni zarezom.",
    guide_col_unavailable_values: "Npr. 05-06-2026, 22-03-2026 do 28-03-2026, 15-12-2026",
    guide_col_preferred_desc: "Datumi kada lekar ŽELI da dežura. Sistem daje prioritet ovim željama.", guide_col_preferred_values: "Npr. 01-06-2026, 20-06-2026",
    guide_col_rank_desc: "Redni broj u timu (za rangirane dežurne)", guide_col_rank_values: "Broj (1, 2, 3, 4, 5...)",
    guide_warning_title: "⚠️ Važne napomene:",
    guide_warning_1: "Sve kolone su obavezne osim \"Ne može\", \"Želi da dežura\" i \"Rang\"",
    guide_warning_2: "Datumi moraju biti u formatu DD-MM-GGGG",
    guide_warning_3: "Za udeo koristite isključivo tekstualne oznake",
    guide_warning_4: "Ne koristite razlomke (1/1, 1/2)!",
    guide_warning_5: "Samo specijalisti mogu imati \"DA\" u koloni \"Može biti glavni\"",
    guide_warning_6: "Kolona 'Rang' je obavezna samo kada se koriste rangirani timovi",
    guide_warning_7: "Opsezi datuma se unose kao: DD-MM-GGGG do DD-MM-GGGG (npr. 22-03-2026 do 28-03-2026). Može i 'to' za engleski.",
    guide_example_title: "📋 Primer Excel fajla",
    guide_example_text: "Preuzmite gotov primer sa 16 lekara (sa rangovima):",
    guide_example_btn_sr: "📥 Preuzmi demo Excel (srpska zaglavlja)",
    guide_example_btn_en: "📥 Preuzmi demo Excel (engleska zaglavlja)",
    guide_example_note: "Primer sadrži 8 specijalista i 8 specijalizanata sa rangovima 1-5.",
    guide_step2_title: "2️⃣ Popunjavanje forme na početnoj strani",
    guide_step2_1_title: "Naziv ustanove", guide_step2_1_text: "Unesite naziv bolnice ili doma zdravlja.",
    guide_step2_2_title: "Mesec i Godina", guide_step2_2_text: "Izaberite mesec i godinu.",
    guide_step2_3_title: "Broj dežurnih po danu", guide_step2_3_text: "Koliko celih dežurstava (1/1) treba popuniti.",
    guide_step2_4_title: "Čekboks za specijaliste", guide_step2_4_text: "Opcija za strožije pravilo.",
    guide_step2_5_title: "Rangirani dežurni", guide_step2_5_text: "Ako je čekirano, zahteva lekare svih rangova.",
    guide_step2_6_title: "Kalendar", guide_step2_6_text: "Kliknite na datume za dežurstva.",
    guide_step2_7_title: "Excel fajl", guide_step2_7_text: "Otpremite pripremljeni Excel fajl.",
    guide_step2_8_title: "Tip 2 dežurstva", guide_step2_8_text: "Ako treba drugi tip dežurstva.",
    guide_step2_9_title: "Prilagođena imena", guide_step2_9_text: "Nazivi za tipove dežurstava.",
    guide_step3_title: "3️⃣ Generisanje i preuzimanje",
    guide_step3_1_title: "Kliknite \"Generiši raspored\"", guide_step3_1_text: "Sistem će obraditi podatke.",
    guide_step3_2_title: "Pregledajte rezultat", guide_step3_2_text: "Tekstualni prikaz se pojavljuje ispod forme.",
    guide_step3_3_title: "Preuzmite Excel", guide_step3_3_text: "Kliknite na dugme za preuzimanje.",
    guide_output_title: "📊 Šta sadrži output Excel?",
    guide_output_sheet_header: "Sheet", guide_output_content_header: "Sadržaj",
    guide_output_sheet1: "Raspored", guide_output_sheet1_desc: "Formatiran prikaz sa statistikom.",
    guide_output_sheet2: "Tabelarni pregled", guide_output_sheet2_desc: "Tabela sa svim podacima.",
    guide_output_sheet3: "Statistika", guide_output_sheet3_desc: "Pregled po lekaru sa opterećenjem.",
    guide_cta_title: "🚀 Spremni da počnete?",
    guide_cta_text: "Preuzmite demo Excel i testirajte sistem.",
    guide_cta_btn: "⚡ Idi na početnu stranu",
  },
  
  en: {
    nav_brand: "🩺 ShiftMD v3.6", nav_home: "🏠 Home", nav_about: "ℹ️ About", nav_guide: "📖 Guide",
    nav_lang_sr: "🇷🇸 SR", nav_lang_en: "🇬🇧 EN",
    
    footer_cikt: "Center for Information and Communication Technologies",
    footer_university: "University of Belgrade, Faculty of Medicine",
    
    page_title: "ShiftMD v3.6 - Duty Schedule",
    heading: "ShiftMD v3.6",
    subtitle: "Physician duty scheduling system",
    form_hospital: "Institution name",
    form_month: "Month", form_year: "Year",
    form_month_placeholder: "Month", form_year_placeholder: "Year",
    
    form_duty_type1_label: "Duty - Type 1",
    form_duty_type2_toggle: "Is an additional duty type needed for other dates?",
    form_duty_type2_label: "Duty - Type 2",
    form_custom_names_label: "Custom duty type names:",
    form_custom_name1_placeholder: "Name for Type 1 (e.g. Regular duty)",
    form_custom_name2_placeholder: "Name for Type 2 (e.g. Emergency duty)",
    form_type1_dates: "Days for Type 1:",
    form_type2_dates: "Days for Type 2:",
    calendar_placeholder_type1: "Select month and year for Type 1",
    calendar_placeholder_type2: "Select month and year for Type 2",
    
    form_duty_count_label: "Number of on-call staff per day:",
    form_duty_count_hint: "How many full duties (1/1) to fill per day",
    form_allow_less_label: "Allow less than 50% specialists among on-call staff?",
    form_allow_less_hint_checked: "If checked: a specialist will be mandatory as chief, but specialist share may be less than 50%.",
    form_allow_less_hint_unchecked: "If NOT checked: at least 50% of on-call staff must be specialists.",
    form_ranked_label: "Ranked duty teams?",
    form_ranked_hint_checked: "If checked: each day must have physicians of all ranks. Staff count = rank count.",
    form_ranked_hint_unchecked: "If NOT checked: standard algorithm distribution.",
    form_excel_label: "📂 Upload Excel file with physician list:",
    form_excel_hint: "Allowed formats: .xlsx, .xls",
    form_demo_link_sr: "📥 Download sample (Serbian headers)",
    form_demo_link_en: "📥 Download sample (English headers)",
    form_submit: "⚡ Generate Schedule",
    calendar_placeholder: "Select month and year to view calendar",
    calendar_error: "Invalid month or year.",
    
    day_mon: "Mon", day_tue: "Tue", day_wed: "Wed", day_thu: "Thu", day_fri: "Fri", day_sat: "Sat", day_sun: "Sun",
    month_1: "January", month_2: "February", month_3: "March", month_4: "April", month_5: "May", month_6: "June",
    month_7: "July", month_8: "August", month_9: "September", month_10: "October", month_11: "November", month_12: "December",
    
    status_loading: "ShiftMD is calculating schedule and generating Excel file...",
    status_success: "✅ ShiftMD: Schedule generated in {duration}s!",
    status_error_no_excel: "Please upload an Excel file.",
    status_error_no_dates: "Please select at least one duty day.",
    status_error_no_dates1: "You must select at least one day for Type 1.",
    status_error_no_dates2: "You must select at least one day for Type 2.",
    status_error_overlap: "Type 1 and Type 2 dates overlap!",
    status_error_no_count: "Number of on-call staff must be at least 1.",
    status_error_no_file: "No generated file to download.",
    
    download_btn: "📥 Download Excel Schedule",
    download_btn_with_name: "📥 Download Excel Schedule ({filename})",
    result_title: "DUTY SCHEDULE",
    result_hospital: "Institution", result_month: "Month", result_duty_count: "Duties per day",
    result_rule: "Rule", result_rule_strict: "Minimum 50% specialists", result_rule_relaxed: "Mandatory chief specialist",
    result_ranked: "Ranked teams", result_time: "Time", result_seconds: "seconds",
    result_no_data: "⚠️ No duties generated.",
    
    about_title: "ℹ️ About ShiftMD",
    about_subtitle: "Intelligent system for fair duty distribution with focus on burnout prevention",
    about_mission_title: "🎯 Our Mission",
    about_mission_text: "ShiftMD was created with one goal: eliminate unfairness in duty scheduling and protect healthcare workers.",
    about_features_title: "✨ Key Features",
    about_feature_1_title: "Fair Distribution", about_feature_1_text: "Advanced algorithm ensures all physicians receive approximately equal workload",
    about_feature_2_title: "Burnout Protection", about_feature_2_text: "Minimum 2 days gap, limited weekends, maximum workload",
    about_feature_3_title: "Respect Preferences", about_feature_3_text: "Physicians can indicate preferred duty dates",
    about_feature_4_title: "\"Unavailable\" Respected", about_feature_4_text: "Dates when a physician cannot work are absolutely respected",
    about_feature_5_title: "Chief on Call", about_feature_5_text: "Automatically assigns a specialist who can be chief",
    about_feature_6_title: "Date Ranges", about_feature_6_text: "Enter vacation as a range: 22-03-2026 to 28-03-2026",
    about_feature_7_title: "Two Duty Types", about_feature_7_text: "Support for different duty types in the same month",
    about_feature_8_title: "Ranked Teams", about_feature_8_text: "Support for surgical teams with ranked on-call staff",
    about_logic_title: "🧠 Workload Distribution Logic & Burnout Prevention",
    about_logic_box_title: "🛡️ Burnout Prevention - Heart of the System",
    about_logic_box_text: "ShiftMD uses a sophisticated scoring algorithm that considers 9 different factors.",
    about_limits_title: "📊 Maximum Limits:",
    about_limit_1: "Max duty days: proportional to number of physicians + 2",
    about_limit_2: "Max workload: 30% of total capacity per physician",
    about_limit_3: "Max weekends: proportional to weekend days and physician count + 1",
    about_limit_4: "Min gap: 2 days between duties (absolute rule)",
    about_cta_title: "🚀 Ready for Fairer Scheduling?",
    about_cta_text: "Return to the home page and generate your first schedule.",
    about_cta_btn: "⚡ Generate Schedule",
    
    guide_title: "📖 User Guide",
    guide_subtitle: "Step by step guide for generating duty schedules",
    guide_step1_title: "1️⃣ Preparing Excel File with Physicians",
    guide_step1_text: "This is the most important step. The Excel file must have exactly specified columns:",
    guide_table_header_col: "Column", guide_table_header_required: "Required", guide_table_header_desc: "Description", guide_table_header_values: "Allowed Values",
    guide_col_name_desc: "Physician's full name", guide_col_name_values: "Any text",
    guide_col_seniority_desc: "Arbitrary value from 1 to 15. Lower number = higher priority", guide_col_seniority_values: "Number from 1 to 15",
    guide_col_chief_desc: "Can this physician be chief on call? (must be specialist)", guide_col_chief_values: "YES/DA or NO/NE",
    guide_col_role_desc: "Physician type", guide_col_role_values: "specialist or resident",
    guide_col_share_desc: "What portion of a full duty", guide_col_share_values: "full, half, third, quarter, eighth",
    guide_col_unavailable_desc: "Dates when physician CANNOT work. Individual dates or ranges ('do'/'to') separated by comma.",
    guide_col_unavailable_values: "E.g. 05-06-2026, 22-03-2026 to 28-03-2026, 15-12-2026",
    guide_col_preferred_desc: "Dates when physician WANTS to work.", guide_col_preferred_values: "E.g. 01-06-2026, 20-06-2026",
    guide_col_rank_desc: "Team position number", guide_col_rank_values: "Number (1, 2, 3, 4, 5...)",
    guide_warning_title: "⚠️ Important Notes:",
    guide_warning_1: "All columns required except \"Unavailable\", \"Preferred\" and \"Rank\"",
    guide_warning_2: "Dates must be in DD-MM-YYYY format",
    guide_warning_3: "For share, use text labels only",
    guide_warning_4: "Do not use fractions (1/1, 1/2)!",
    guide_warning_5: "Only specialists can have \"YES\" in \"Can be Chief\"",
    guide_warning_6: "'Rank' only required for ranked teams",
    guide_warning_7: "Date ranges: DD-MM-YYYY to DD-MM-YYYY (e.g. 22-03-2026 to 28-03-2026). 'do' also works.",
    guide_example_title: "📋 Sample Excel File",
    guide_example_text: "Download a ready-made example with 16 physicians:",
    guide_example_btn_sr: "📥 Download demo Excel (Serbian headers)",
    guide_example_btn_en: "📥 Download demo Excel (English headers)",
    guide_example_note: "Example contains 8 specialists and 8 residents with ranks 1-5.",
    guide_step2_title: "2️⃣ Filling the Form",
    guide_step2_1_title: "Institution Name", guide_step2_1_text: "Enter hospital or clinic name.",
    guide_step2_2_title: "Month and Year", guide_step2_2_text: "Select month and year.",
    guide_step2_3_title: "Number of On-Call Staff", guide_step2_3_text: "How many full duties (1/1) to fill.",
    guide_step2_4_title: "Specialist Checkbox", guide_step2_4_text: "Option for stricter rule.",
    guide_step2_5_title: "Ranked Duties", guide_step2_5_text: "If checked, requires all ranks each day.",
    guide_step2_6_title: "Calendar", guide_step2_6_text: "Click on dates for duties.",
    guide_step2_7_title: "Excel File", guide_step2_7_text: "Upload the prepared Excel file.",
    guide_step2_8_title: "Type 2 Duty", guide_step2_8_text: "If a second duty type is needed.",
    guide_step2_9_title: "Custom Names", guide_step2_9_text: "Names for duty types.",
    guide_step3_title: "3️⃣ Generation and Download",
    guide_step3_1_title: "Click \"Generate Schedule\"", guide_step3_1_text: "System will process data.",
    guide_step3_2_title: "Review Result", guide_step3_2_text: "Text display appears below form.",
    guide_step3_3_title: "Download Excel", guide_step3_3_text: "Click the download button.",
    guide_output_title: "📊 What Does the Output Excel Contain?",
    guide_output_sheet_header: "Sheet", guide_output_content_header: "Content",
    guide_output_sheet1: "Schedule", guide_output_sheet1_desc: "Formatted view with statistics.",
    guide_output_sheet2: "Table View", guide_output_sheet2_desc: "Table with all data.",
    guide_output_sheet3: "Statistics", guide_output_sheet3_desc: "Per physician overview.",
    guide_cta_title: "🚀 Ready to Start?",
    guide_cta_text: "Download the demo Excel and test the system.",
    guide_cta_btn: "⚡ Go to Home Page",
  }
};

function t(lang, key, replacements = {}) {
  let text = translations[lang]?.[key] || translations['sr']?.[key] || key;
  Object.keys(replacements).forEach(k => { text = text.replace(`{${k}}`, replacements[k]); });
  return text;
}

if (typeof module !== 'undefined') {
  module.exports = { translations, t };
}