// ShiftMD v3.0 - Dvojezični sistem (srpski i engleski)
// Svi vidljivi stringovi su ovde

const translations = {
  sr: {
    // Navigacija
    nav_brand: "🩺 ShiftMD v3.0",
    nav_home: "🏠 Početna",
    nav_about: "ℹ️ O sistemu",
    nav_guide: "📖 Uputstvo",
    nav_lang_sr: "🇷🇸 SR",
    nav_lang_en: "🇬🇧 EN",
    
    // Index strana
    page_title: "ShiftMD v3.0 - Raspored dežurstava",
    heading: "ShiftMD v3.0",
    subtitle: "Sistem za raspored dežurstava lekara",
    form_hospital: "Naziv ustanove",
    form_month: "Mesec",
    form_year: "Godina",
    form_month_placeholder: "Mesec",
    form_year_placeholder: "Godina",
    form_duty_count_label: "Broj dežurnih po danu:",
    form_duty_count_hint: "Koliko ukupno dežurstava (1/1) treba popuniti po danu",
    form_allow_less_label: "Dozvoli da bude manje od 50% specijalista među dežurnima?",
    form_allow_less_hint_checked: "Ako je čekirano: specijalista će obavezno biti glavni dežurni za taj dan, ali ukupan udeo specijalista može biti manji od 50%.",
    form_allow_less_hint_unchecked: "Ako NIJE čekirano: najmanje 50% dežurnih moraju biti specijalisti.",
    form_excel_label: "📂 Otpremite Excel fajl sa spiskom lekara:",
    form_excel_hint: "Dozvoljeni formati: .xlsx, .xls",
    form_demo_link: "📥 Preuzmi primer Excel fajla",
    form_submit: "⚡ Generiši raspored",
    calendar_placeholder: "Izaberite mesec i godinu da biste videli kalendar",
    calendar_error: "Neispravan mesec ili godina.",
    
    // Calendar days
    day_mon: "Pon",
    day_tue: "Uto",
    day_wed: "Sre",
    day_thu: "Čet",
    day_fri: "Pet",
    day_sat: "Sub",
    day_sun: "Ned",
    
    // Months
    month_1: "Januar",
    month_2: "Februar",
    month_3: "Mart",
    month_4: "April",
    month_5: "Maj",
    month_6: "Jun",
    month_7: "Jul",
    month_8: "Avgust",
    month_9: "Septembar",
    month_10: "Oktobar",
    month_11: "Novembar",
    month_12: "Decembar",
    
    // Status messages
    status_loading: "ShiftMD računa raspored i generiše Excel fajl...",
    status_success: "✅ ShiftMD: Raspored generisan za {duration}s!",
    status_error_no_excel: "Molimo otpremite Excel fajl.",
    status_error_no_dates: "Izaberite bar jedan dan dežurstva.",
    status_error_no_count: "Broj dežurnih po danu mora biti najmanje 1.",
    status_error_no_file: "Nema generisanog fajla za preuzimanje.",
    
    // Result
    download_btn: "📥 Preuzmi Excel raspored",
    download_btn_with_name: "📥 Preuzmi Excel raspored ({filename})",
    result_title: "RASPORED DEŽURSTAVA",
    result_hospital: "Ustanova",
    result_month: "Mesec",
    result_duty_count: "Broj dežurstava po danu",
    result_rule: "Pravilo",
    result_rule_strict: "Minimum 50% specijalista",
    result_rule_relaxed: "Obavezan glavni specijalista",
    result_time: "Vreme",
    result_seconds: "sekundi",
    result_no_data: "⚠️ Nema generisanih dežurstava.",
    
    // Footer
    footer_text: "ShiftMD v3.0 © 2026 - Sistem za raspored dežurstava",
    
    // O sistemu strana
    about_title: "ℹ️ O sistemu ShiftMD",
    about_subtitle: "Inteligentni sistem za pravednu raspodelu dežurstava sa fokusom na sprečavanje burnout-a",
    about_mission_title: "🎯 Naša misija",
    about_mission_text: "ShiftMD je stvoren sa jednim ciljem: eliminisati nepravdu u raspodeli dežurstava i zaštititi zdravstvene radnike od prekomernog opterećenja. Verujemo da pravedan raspored direktno utiče na kvalitet nege pacijenata i zadovoljstvo lekara.",
    about_features_title: "✨ Ključne mogućnosti",
    about_feature_1_title: "Pravedna raspodela",
    about_feature_1_text: "Napredni algoritam osigurava da svi lekari dobiju približno isto opterećenje",
    about_feature_2_title: "Burnout zaštita",
    about_feature_2_text: "Minimum 2 dana razmaka, limitirani vikendi, maksimalno opterećenje po lekaru",
    about_feature_3_title: "Poštovanje želja",
    about_feature_3_text: "Lekari mogu naznačiti datume kada žele da dežuraju - sistem im daje prioritet",
    about_feature_4_title: "\"Ne može\" se poštuje",
    about_feature_4_text: "Datumi kada lekar ne može da dežura se apsolutno poštuju, bez izuzetaka",
    about_feature_5_title: "Glavni dežurni",
    about_feature_5_text: "Automatski dodeljuje specijalistu koji može biti glavni za svako dežurstvo",
    about_feature_6_title: "Detaljna statistika",
    about_feature_6_text: "Max, prosek i min opterećenje, broj dežurstava i vikenda za svakog lekara",
    about_logic_title: "🧠 Logika rasterećenja i sprečavanja burnout-a",
    about_logic_box_title: "🛡️ Burnout prevencija - srce sistema",
    about_logic_box_text: "ShiftMD koristi sofisticirani scoring algoritam koji uzima u obzir 9 različitih faktora kako bi doneo najpravedniju odluku o dodeli dežurstva.",
    about_scoring_title: "📐 Kako funkcioniše scoring?",
    about_scoring_text: "Svaki lekar dobija numerički \"skor\" (trošak dodele). Manji skor = veća šansa da dobije dežurstvo. Sistem se trudi da svi lekari imaju približno isti skor, čime se postiže prirodna ravnoteža.",
    about_factors_title: "🔢 Faktori scoringa (9 nivoa zaštite):",
    about_factor_1: "Ukupno opterećenje (×50) - Najvažniji faktor. Što više dežurstava lekar već ima, to mu je veći skor i manja šansa za novo dežurstvo.",
    about_factor_2: "Broj dežurstava sa kvadratnom kaznom - Za prvih 3 dežurstva normalna kazna, za svako sledeće eksponencijalno raste.",
    about_factor_3: "Vikend zaštita (×25) - Vikend dežurstva su posebno \"kažnjena\". Sistem proverava da li je lekar radio vikend u poslednjih 14 dana.",
    about_factor_4: "Gustina dežurstava - Prati prosečan razmak između svih dežurstava. Idealni razmak je 4+ dana.",
    about_factor_5: "Razmak od poslednjeg (×5 bonus/dan) - Veći razmak = manji skor. Minimum 2 dana razmaka se strogo poštuje.",
    about_factor_6: "Starešinstvo (kategorijski ×20) - 5 kategorija. Mlađi lekari imaju prednost pri dodeli.",
    about_factor_7: "Poređenje sa prosekom - Lekari iznad proseka opterećenja dobijaju dodatnu kaznu.",
    about_factor_8: "Udeo dežurstva - Bonus ako udeo lekara tačno odgovara \"rupici\" u rasporedu.",
    about_factor_9: "Želje (bonus -30) - Lekari koji su izrazili želju za određeni datum dobijaju značajan bonus.",
    about_limits_title: "📊 Maksimalni limiti:",
    about_limit_1: "Max dana dežurstva: proporcionalno broju lekara + 2 dana tolerancije",
    about_limit_2: "Max opterećenje: 30% ukupnog kapaciteta po lekaru",
    about_limit_3: "Max vikenda: proporcionalno broju vikend dana i broju lekara + 1",
    about_limit_4: "Min razmak: 2 dana između dežurstava (apsolutno pravilo)",
    about_process_title: "🔄 Proces dodele (korak po korak)",
    about_step_1_title: "Glavni dežurni",
    about_step_1_text: "Prvo se dodeljuje specijalista koji može biti glavni. Prednost ima onaj ko je tražio taj datum.",
    about_step_2_title: "Želje",
    about_step_2_text: "Zatim se dodeljuju lekari koji su izrazili želju za taj datum, sortirani po višem starešinstvu.",
    about_step_3_title: "Popuna",
    about_step_3_text: "Ostatak se popunjava po scoringu. Ako lekar ima udeo manji od 1/1, sistem odmah traži sledećeg.",
    about_step_4_title: "Validacija",
    about_step_4_text: "Provera da li svako dežurstvo ima glavnog i (opciono) minimum 50% specijalista.",
    about_cta_title: "🚀 Spremni za pravednije dežurstvo?",
    about_cta_text: "Vratite se na početnu stranu i generišite svoj prvi raspored.",
    about_cta_btn: "⚡ Generiši raspored",
    
    // Uputstvo strana
    guide_title: "📖 Uputstvo za korišćenje",
    guide_subtitle: "Korak po korak vodič za generisanje rasporeda dežurstava",
    guide_step1_title: "1️⃣ Priprema Excel fajla sa lekarima",
    guide_step1_text: "Ovo je najvažniji korak. Excel fajl mora imati tačno određene kolone sa ispravnim nazivima:",
    guide_table_header_col: "Kolona",
    guide_table_header_required: "Obavezno",
    guide_table_header_desc: "Opis",
    guide_table_header_values: "Dozvoljene vrednosti",
    guide_col_name: "Ime i prezime",
    guide_col_name_desc: "Puno ime i prezime lekara",
    guide_col_name_values: "Bilo koji tekst (npr. Dr Marko Marković)",
    guide_col_seniority: "Starešinstvo",
    guide_col_seniority_desc: "Broj godina staža. Manji broj = mlađi lekar = veći prioritet",
    guide_col_seniority_values: "Broj (npr. 5, 10, 15)",
    guide_col_chief: "Može biti glavni",
    guide_col_chief_desc: "Da li lekar može biti glavni dežurni? (mora biti specijalista)",
    guide_col_chief_values: "DA ili NE",
    guide_col_role: "Tip zaposlenog",
    guide_col_role_desc: "Vrsta lekara",
    guide_col_role_values: "specijalista ili specijalizant",
    guide_col_share: "Udeo dežurstva",
    guide_col_share_desc: "Koliki deo punog dežurstva lekar može da pokrije",
    guide_col_share_values: "celo, polovina, trećina, četvrtina, osmina",
    guide_col_unavailable: "Ne može",
    guide_col_unavailable_desc: "Datumi kada lekar NE MOŽE da dežura. Više datuma odvojiti zarezom.",
    guide_col_unavailable_values: "Npr. 05-06-2026, 15-06-2026",
    guide_col_preferred: "Želi da dežura",
    guide_col_preferred_desc: "Datumi kada lekar ŽELI da dežura. Sistem daje prioritet ovim željama.",
    guide_col_preferred_values: "Npr. 01-06-2026, 20-06-2026",
    guide_warning_title: "⚠️ Važne napomene:",
    guide_warning_1: "Sve kolone su obavezne osim \"Ne može\" i \"Želi da dežura\"",
    guide_warning_2: "Datumi moraju biti u formatu DD-MM-GGGG (npr. 15-06-2026)",
    guide_warning_3: "Za udeo koristite isključivo tekstualne oznake: celo, polovina, trećina, četvrtina, osmina",
    guide_warning_4: "Ne koristite razlomke (1/1, 1/2) jer ih Excel može pretvoriti u datume!",
    guide_warning_5: "Samo specijalisti mogu imati \"DA\" u koloni \"Može biti glavni\"",
    guide_example_title: "📋 Primer Excel fajla",
    guide_example_text: "Preuzmite gotov primer sa 16 lekara koji možete koristiti za testiranje:",
    guide_example_btn: "📥 Preuzmi demo Excel fajl (16 lekara)",
    guide_example_note: "Primer sadrži 8 specijalista i 8 specijalizanata sa različitim udelima, datumima nedostupnosti i željama.",
    guide_step2_title: "2️⃣ Popunjavanje forme na početnoj strani",
    guide_step2_1_title: "Naziv ustanove",
    guide_step2_1_text: "Unesite naziv bolnice ili doma zdravlja. Ovo će se pojaviti u zaglavlju izveštaja.",
    guide_step2_2_title: "Mesec i Godina",
    guide_step2_2_text: "Izaberite mesec i godinu za koje pravite raspored. Kalendar će se automatski prikazati.",
    guide_step2_3_title: "Broj dežurnih po danu",
    guide_step2_3_text: "Koliko celih dežurstava (1/1) treba popuniti svakog dana.",
    guide_step2_4_title: "Čekboks za specijaliste",
    guide_step2_4_text: "Ako je čekirano: dozvoljeno manje od 50% specijalista. Ako nije: minimum 50% specijalista.",
    guide_step2_5_title: "Kalendar",
    guide_step2_5_text: "Kliknite na datume kada treba organizovati dežurstva. Izabrani datumi postaju plavi.",
    guide_step2_6_title: "Excel fajl",
    guide_step2_6_text: "Otpremite pripremljeni Excel fajl sa spiskom lekara.",
    guide_step3_title: "3️⃣ Generisanje i preuzimanje",
    guide_step3_1_title: "Kliknite \"Generiši raspored\"",
    guide_step3_1_text: "Sistem će obraditi podatke i prikazati rezultat.",
    guide_step3_2_title: "Pregledajte rezultat",
    guide_step3_2_text: "Tekstualni prikaz rasporeda se pojavljuje ispod forme.",
    guide_step3_3_title: "Preuzmite Excel",
    guide_step3_3_text: "Kliknite na dugme za preuzimanje. Fajl će biti sačuvan.",
    guide_output_title: "📊 Šta sadrži output Excel?",
    guide_output_sheet1: "Raspored",
    guide_output_sheet1_desc: "Formatiran prikaz sa statistikom, zaglavljem, svim dežurstvima po datumima.",
    guide_output_sheet2: "Tabelarni pregled",
    guide_output_sheet2_desc: "Tabela sa kolonama: Datum, Dan, Dežurstvo, Ime, Tip, Udeo, Glavni.",
    guide_output_sheet3: "Statistika",
    guide_output_sheet3_desc: "Pregled po lekaru: opterećenje, broj dežurstava, vikenda, obojeno po intenzitetu.",
    guide_cta_title: "🚀 Spremni da počnete?",
    guide_cta_text: "Preuzmite demo Excel, otpremite ga na početnoj strani i testirajte sistem.",
    guide_cta_btn: "⚡ Idi na početnu stranu",
    
    // Excel output
    excel_sheet_raspored: "Raspored",
    excel_sheet_table: "Tabelarni pregled",
    excel_sheet_stats: "Statistika",
    excel_title: "RASPORED DEŽURSTAVA",
    excel_period: "godine",
    excel_duty_count: "Broj dežurstava po danu",
    excel_rule: "Pravilo",
    excel_generated: "Generisano",
    excel_stats_title: "📊 STATISTIKA OPTEREĆENJA",
    excel_stats_load: "Opterećenje (skor)",
    excel_stats_duties: "Broj dežurstava",
    excel_stats_weekends: "Vikend dežurstva",
    excel_max: "Maksimum",
    excel_avg: "Prosek",
    excel_min: "Minimum",
    excel_total_doctors: "Ukupno lekara",
    excel_with_duties: "Sa dežurstvima",
    excel_without_duties: "Bez",
    excel_period_label: "Period",
    excel_days: "dana",
    excel_duty_slot: "Dežurstvo",
    excel_chief: "GLAVNI DEŽURNI",
    excel_specialist: "Specijalista",
    excel_resident: "Specijalizant",
    excel_yes: "DA",
    excel_no: "NE",
    excel_share_celo: "celo",
    excel_share_half: "polovina",
    excel_share_third: "trećina",
    excel_share_quarter: "četvrtina",
    excel_share_eighth: "osmina",
  },
  
  en: {
    // Navigation
    nav_brand: "🩺 ShiftMD v3.0",
    nav_home: "🏠 Home",
    nav_about: "ℹ️ About",
    nav_guide: "📖 Guide",
    nav_lang_sr: "🇷🇸 SR",
    nav_lang_en: "🇬🇧 EN",
    
    // Index page
    page_title: "ShiftMD v3.0 - Duty Schedule",
    heading: "ShiftMD v3.0",
    subtitle: "Physician duty scheduling system",
    form_hospital: "Institution name",
    form_month: "Month",
    form_year: "Year",
    form_month_placeholder: "Month",
    form_year_placeholder: "Year",
    form_duty_count_label: "Number of on-call staff per day:",
    form_duty_count_hint: "How many full duties (1/1) to fill per day",
    form_allow_less_label: "Allow less than 50% specialists among on-call staff?",
    form_allow_less_hint_checked: "If checked: a specialist will be mandatory as chief on-call, but total specialist share may be less than 50%.",
    form_allow_less_hint_unchecked: "If NOT checked: at least 50% of on-call staff must be specialists.",
    form_excel_label: "📂 Upload Excel file with physician list:",
    form_excel_hint: "Allowed formats: .xlsx, .xls",
    form_demo_link: "📥 Download sample Excel file",
    form_submit: "⚡ Generate Schedule",
    calendar_placeholder: "Select month and year to view calendar",
    calendar_error: "Invalid month or year.",
    
    // Calendar days
    day_mon: "Mon",
    day_tue: "Tue",
    day_wed: "Wed",
    day_thu: "Thu",
    day_fri: "Fri",
    day_sat: "Sat",
    day_sun: "Sun",
    
    // Months
    month_1: "January",
    month_2: "February",
    month_3: "March",
    month_4: "April",
    month_5: "May",
    month_6: "June",
    month_7: "July",
    month_8: "August",
    month_9: "September",
    month_10: "October",
    month_11: "November",
    month_12: "December",
    
    // Status messages
    status_loading: "ShiftMD is calculating schedule and generating Excel file...",
    status_success: "✅ ShiftMD: Schedule generated in {duration}s!",
    status_error_no_excel: "Please upload an Excel file.",
    status_error_no_dates: "Please select at least one duty day.",
    status_error_no_count: "Number of on-call staff must be at least 1.",
    status_error_no_file: "No generated file to download.",
    
    // Result
    download_btn: "📥 Download Excel Schedule",
    download_btn_with_name: "📥 Download Excel Schedule ({filename})",
    result_title: "DUTY SCHEDULE",
    result_hospital: "Institution",
    result_month: "Month",
    result_duty_count: "Duties per day",
    result_rule: "Rule",
    result_rule_strict: "Minimum 50% specialists",
    result_rule_relaxed: "Mandatory chief specialist",
    result_time: "Time",
    result_seconds: "seconds",
    result_no_data: "⚠️ No duties generated.",
    
    // Footer
    footer_text: "ShiftMD v3.0 © 2026 - Duty Scheduling System",
    
    // About page
    about_title: "ℹ️ About ShiftMD",
    about_subtitle: "Intelligent system for fair duty distribution with focus on burnout prevention",
    about_mission_title: "🎯 Our Mission",
    about_mission_text: "ShiftMD was created with one goal: eliminate unfairness in duty scheduling and protect healthcare workers from excessive workload. We believe that a fair schedule directly impacts patient care quality and physician satisfaction.",
    about_features_title: "✨ Key Features",
    about_feature_1_title: "Fair Distribution",
    about_feature_1_text: "Advanced algorithm ensures all physicians receive approximately equal workload",
    about_feature_2_title: "Burnout Protection",
    about_feature_2_text: "Minimum 2 days gap, limited weekends, maximum workload per physician",
    about_feature_3_title: "Respect Preferences",
    about_feature_3_text: "Physicians can indicate preferred duty dates - the system prioritizes them",
    about_feature_4_title: "\"Unavailable\" Respected",
    about_feature_4_text: "Dates when a physician cannot work are absolutely respected, without exceptions",
    about_feature_5_title: "Chief on Call",
    about_feature_5_text: "Automatically assigns a specialist who can be chief for each duty",
    about_feature_6_title: "Detailed Statistics",
    about_feature_6_text: "Max, average and min workload, number of duties and weekends per physician",
    about_logic_title: "🧠 Workload Distribution Logic & Burnout Prevention",
    about_logic_box_title: "🛡️ Burnout Prevention - Heart of the System",
    about_logic_box_text: "ShiftMD uses a sophisticated scoring algorithm that considers 9 different factors to make the fairest duty assignment decision.",
    about_scoring_title: "📐 How Does Scoring Work?",
    about_scoring_text: "Each physician receives a numeric \"score\" (assignment cost). Lower score = higher chance of getting the duty. The system strives to keep all physicians at approximately the same score, achieving natural balance.",
    about_factors_title: "🔢 Scoring Factors (9 Levels of Protection):",
    about_factor_1: "Total workload (×50) - Most important factor. More duties = higher score = lower chance for new duty.",
    about_factor_2: "Duty count with quadratic penalty - Normal penalty for first 3 duties, exponential increase for each additional.",
    about_factor_3: "Weekend protection (×25) - Weekend duties are specially penalized. Checks if physician worked weekend in last 14 days.",
    about_factor_4: "Duty density - Tracks average gap between all duties. Ideal gap is 4+ days.",
    about_factor_5: "Gap since last duty (×5 bonus/day) - Larger gap = lower score. Minimum 2-day gap strictly enforced.",
    about_factor_6: "Seniority (category ×20) - 5 categories. Junior physicians have priority in assignment.",
    about_factor_7: "Average comparison - Physicians above average workload receive additional penalty.",
    about_factor_8: "Duty share - Bonus if physician's share exactly matches the \"gap\" in the schedule.",
    about_factor_9: "Preferences (bonus -30) - Physicians who expressed preference for a date get significant bonus.",
    about_limits_title: "📊 Maximum Limits:",
    about_limit_1: "Max duty days: proportional to number of physicians + 2 days tolerance",
    about_limit_2: "Max workload: 30% of total capacity per physician",
    about_limit_3: "Max weekends: proportional to weekend days and physician count + 1",
    about_limit_4: "Min gap: 2 days between duties (absolute rule)",
    about_process_title: "🔄 Assignment Process (Step by Step)",
    about_step_1_title: "Chief on Call",
    about_step_1_text: "First, a specialist who can be chief is assigned. Priority to those who requested this date.",
    about_step_2_title: "Preferences",
    about_step_2_text: "Then physicians who expressed preference for this date are assigned, sorted by higher seniority.",
    about_step_3_title: "Fill Remaining",
    about_step_3_text: "Remainder filled by scoring. If physician has share < 1/1, system immediately looks for next to fill gap.",
    about_step_4_title: "Validation",
    about_step_4_text: "Check that each duty has a chief and (optionally) minimum 50% specialists.",
    about_cta_title: "🚀 Ready for Fairer Scheduling?",
    about_cta_text: "Return to the home page and generate your first schedule.",
    about_cta_btn: "⚡ Generate Schedule",
    
    // Guide page
    guide_title: "📖 User Guide",
    guide_subtitle: "Step by step guide for generating duty schedules",
    guide_step1_title: "1️⃣ Preparing Excel File with Physicians",
    guide_step1_text: "This is the most important step. The Excel file must have exactly specified columns with correct names:",
    guide_table_header_col: "Column",
    guide_table_header_required: "Required",
    guide_table_header_desc: "Description",
    guide_table_header_values: "Allowed Values",
    guide_col_name: "Full Name",
    guide_col_name_desc: "Physician's full name",
    guide_col_name_values: "Any text (e.g. Dr Marko Marković)",
    guide_col_seniority: "Seniority",
    guide_col_seniority_desc: "Years of experience. Lower number = junior physician = higher priority",
    guide_col_seniority_values: "Number (e.g. 5, 10, 15)",
    guide_col_chief: "Can be Chief",
    guide_col_chief_desc: "Can this physician be chief on call? (must be specialist)",
    guide_col_chief_values: "YES or NO",
    guide_col_role: "Employee Type",
    guide_col_role_desc: "Physician type",
    guide_col_role_values: "specialist or resident",
    guide_col_share: "Duty Share",
    guide_col_share_desc: "What portion of a full duty can the physician cover",
    guide_col_share_values: "full, half, third, quarter, eighth",
    guide_col_unavailable: "Unavailable",
    guide_col_unavailable_desc: "Dates when physician CANNOT work. Multiple dates separated by comma.",
    guide_col_unavailable_values: "E.g. 05-06-2026, 15-06-2026",
    guide_col_preferred: "Preferred",
    guide_col_preferred_desc: "Dates when physician WANTS to work. System prioritizes these preferences.",
    guide_col_preferred_values: "E.g. 01-06-2026, 20-06-2026",
    guide_warning_title: "⚠️ Important Notes:",
    guide_warning_1: "All columns are required except \"Unavailable\" and \"Preferred\"",
    guide_warning_2: "Dates must be in DD-MM-YYYY format (e.g. 15-06-2026)",
    guide_warning_3: "For share, use text labels only: full, half, third, quarter, eighth",
    guide_warning_4: "Do not use fractions (1/1, 1/2) as Excel may convert them to dates!",
    guide_warning_5: "Only specialists can have \"YES\" in \"Can be Chief\" column",
    guide_example_title: "📋 Sample Excel File",
    guide_example_text: "Download a ready-made example with 16 physicians for testing:",
    guide_example_btn: "📥 Download Demo Excel File (16 physicians)",
    guide_example_note: "Example contains 8 specialists and 8 residents with different shares, unavailable dates and preferences.",
    guide_step2_title: "2️⃣ Filling the Form on Home Page",
    guide_step2_1_title: "Institution Name",
    guide_step2_1_text: "Enter hospital or clinic name. This will appear in the report header.",
    guide_step2_2_title: "Month and Year",
    guide_step2_2_text: "Select month and year for scheduling. Calendar will automatically display.",
    guide_step2_3_title: "Number of On-Call Staff",
    guide_step2_3_text: "How many full duties (1/1) to fill each day.",
    guide_step2_4_title: "Specialist Checkbox",
    guide_step2_4_text: "If checked: less than 50% specialists allowed. If not: minimum 50% specialists required.",
    guide_step2_5_title: "Calendar",
    guide_step2_5_text: "Click on dates requiring duties. Selected dates turn blue.",
    guide_step2_6_title: "Excel File",
    guide_step2_6_text: "Upload the prepared Excel file with physician list.",
    guide_step3_title: "3️⃣ Generation and Download",
    guide_step3_1_title: "Click \"Generate Schedule\"",
    guide_step3_1_text: "The system will process data and display the result.",
    guide_step3_2_title: "Review Result",
    guide_step3_2_text: "Text display of schedule appears below the form.",
    guide_step3_3_title: "Download Excel",
    guide_step3_3_text: "Click the download button. File will be saved.",
    guide_output_title: "📊 What Does the Output Excel Contain?",
    guide_output_sheet1: "Schedule",
    guide_output_sheet1_desc: "Formatted view with statistics, header, all duties by date.",
    guide_output_sheet2: "Table View",
    guide_output_sheet2_desc: "Table with columns: Date, Day, Duty, Name, Type, Share, Chief.",
    guide_output_sheet3: "Statistics",
    guide_output_sheet3_desc: "Per physician overview: workload, duty count, weekends, color-coded by intensity.",
    guide_cta_title: "🚀 Ready to Start?",
    guide_cta_text: "Download the demo Excel, upload it on the home page and test the system.",
    guide_cta_btn: "⚡ Go to Home Page",
    
    // Excel output
    excel_sheet_raspored: "Schedule",
    excel_sheet_table: "Table View",
    excel_sheet_stats: "Statistics",
    excel_title: "DUTY SCHEDULE",
    excel_period: "",
    excel_duty_count: "Duties per day",
    excel_rule: "Rule",
    excel_generated: "Generated",
    excel_stats_title: "📊 WORKLOAD STATISTICS",
    excel_stats_load: "Workload (score)",
    excel_stats_duties: "Number of Duties",
    excel_stats_weekends: "Weekend Duties",
    excel_max: "Maximum",
    excel_avg: "Average",
    excel_min: "Minimum",
    excel_total_doctors: "Total Physicians",
    excel_with_duties: "With Duties",
    excel_without_duties: "Without",
    excel_period_label: "Period",
    excel_days: "days",
    excel_duty_slot: "Duty",
    excel_chief: "CHIEF ON CALL",
    excel_specialist: "Specialist",
    excel_resident: "Resident",
    excel_yes: "YES",
    excel_no: "NO",
    excel_share_full: "full",
    excel_share_half: "half",
    excel_share_third: "third",
    excel_share_quarter: "quarter",
    excel_share_eighth: "eighth",
  }
};

// Funkcija za dobijanje prevoda
function t(lang, key, replacements = {}) {
  let text = translations[lang]?.[key] || translations['sr']?.[key] || key;
  
  // Zameni {placeholdere}
  Object.keys(replacements).forEach(k => {
    text = text.replace(`{${k}}`, replacements[k]);
  });
  
  return text;
}

// Export za Node.js
if (typeof module !== 'undefined') {
  module.exports = { translations, t };
}